### ISSUE TITLE
ImportError: cannot import name 'RetryWarning'

### ISSUE THREAD

**Issue by dmitry-sobolev** [shveenkov/aiotarantool#12]
Hello,

It seems like current version of aiotarantool (1.1.3) is incompatible with tarantool lib >=0.5.5 because class `RetryWarning` and const `RETRY_MAX_ATTEMPTS` were removed. 

When user trying to use library, he gets errors like one below:

```
/usr/local/lib/python3.6/site-packages/aiotarantool.py:32: in <module>
    from tarantool.error import (
E   ImportError: cannot import name 'RetryWarning'
```

**Comment by shveenkov** [comment]
try update from master

**Comment by dmitry-sobolev** [comment]
Everything is ok now
