### ISSUE TITLE
Python 3.5 features

### ISSUE THREAD

**Issue by Skorpyon** [shveenkov/aiotarantool#7]
Скажите, а будет ли апдейт на async/await или надо самому велосипедить?

**Comment by shveenkov** [comment]
Используйте async/await у себя в коде.
Все должно работать с aiotarantool.

Можете привести конкретный пример, что именно не работает?

**Comment by Skorpyon** [comment]
Просто насколько я понял в 3.5 переписали asyncio и async/await, как синтаксис встроенный,  работают быстрее чем оборачивание в декораторы с корутинами.

**Comment by Skorpyon** [comment]
Огонь!

**Comment by valentinmk** [comment]
@shveenkov Посмотри, пожайлуста, пулл реквест. У меня не завелось с первого раза.
В pypi лежит сейчас багованая версия (я тестировал на 3.5.3 и 3.6.1)
@Skorpyon спасибо, что поднял вопрос. А то я как те ежики, ел кактус ...

**Comment by shveenkov** [comment]
@valentinmk влил правки, спасибо!
